# Generated by Django 4.0.2 on 2022-02-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('price', models.PositiveSmallIntegerField()),
                ('date_added', models.DateTimeField()),
                ('counter', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
