# Generated by Django 4.0.2 on 2022-02-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(choices=[('scientific', 'Scientific'), ('religious', 'Religious'), ('psychology', 'Psychology'), ('roman', 'Roman')], default='psychology', max_length=10),
        ),
    ]
