# Generated by Django 4.0.2 on 2022-02-16 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_book_person_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='person',
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book01', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='givebookone', to='books.book')),
                ('book02', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='givebooktwo', to='books.book')),
                ('book03', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='givebookthree', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
