# Generated by Django 4.0.2 on 2022-02-16 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_person_book01_alter_person_book02_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='book02',
        ),
        migrations.RemoveField(
            model_name='person',
            name='book03',
        ),
    ]
