# Generated by Django 4.0.2 on 2022-02-16 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_person_book02_person_book03_alter_person_book01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='book01',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='givebookone', to='books.book'),
        ),
    ]
