# Generated by Django 4.0.2 on 2022-02-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='counter',
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('basy', 'Basy'), ('free', 'Free')], default='free', max_length=10),
        ),
    ]
