# Generated by Django 4.0.2 on 2022-02-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_requestbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='text_to_admin',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
